name: Build and Publish EZKL iOS SPM package

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "The tag to release"
        required: true
  push:
    tags:
      - "*"

jobs:
  build-and-update:
    runs-on: macos-latest

    steps:
      - name: Checkout EZKL
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Build EzklCoreBindings
        run: CONFIGURATION=release cargo run --bin ios_gen_bindings --features "ios-bindings uuid camino uniffi_bindgen" --no-default-features

      - name: Clone ezkl-swift-package repository
        run: |
          git clone https://github.com/zkonduit/ezkl-swift-package.git

      - name: Copy EzklCoreBindings
        run: |
          rm -rf ezkl-swift-package/Sources/EzklCoreBindings
          cp -r build/EzklCoreBindings ezkl-swift-package/Sources/

      - name: Copy Test Files
        run: |
          rm -rf ezkl-swift-package/Tests/EzklAssets/*
          
          cp tests/assets/kzg ezkl-swift-package/Tests/EzklAssets/kzg.srs
          cp tests/assets/input.json ezkl-swift-package/Tests/EzklAssets/input.json
          cp tests/assets/model.compiled ezkl-swift-package/Tests/EzklAssets/network.ezkl
          cp tests/assets/settings.json ezkl-swift-package/Tests/EzklAssets/settings.json

      - name: Set up Xcode environment
        run: |
          sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
          sudo xcodebuild -license accept

      - name: Run Package Tests
        run: |
          cd ezkl-swift-package
          xcodebuild test \
            -scheme EzklPackage \
            -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.5' \
            -resultBundlePath ../testResults

      - name: Run Example App Tests
        run: |
          cd ezkl-swift-package/Example
          xcodebuild test \
            -project Example.xcodeproj \
            -scheme EzklApp \
            -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.5' \
            -parallel-testing-enabled NO \
            -resultBundlePath ../../exampleTestResults \
            -skip-testing:EzklAppUITests/EzklAppUITests/testButtonClicksInOrder

      - name: Commit and Push Changes to feat/ezkl-direct-integration
        run: |
          cd ezkl-swift-package
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add Sources/EzklCoreBindings
          git add Tests/EzklAssets
          git commit -m "Automatically updated EzklCoreBindings for EZKL"
          git tag ${{ github.event.inputs.tag }}
          git remote set-url origin https://zkonduit:${EZKL_PORTER_TOKEN}@github.com/zkonduit/ezkl-swift-package.git
          git push origin
          git push origin tag ${{ github.event.inputs.tag }}
        env:
          EZKL_PORTER_TOKEN: ${{ secrets.EZKL_PORTER_TOKEN }}